apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: heart-api
  template:
    metadata:
      labels:
        app: heart-api
    spec:
      containers:
      - name: heart-api-container
        
        image: ghcr.io/suvamrx/mlops_assignment1:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: heart-api-service
spec:
  type: LoadBalancer  
  selector:
    app: heart-api
  ports:
    - port: 80
      targetPort: 8000